server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource         #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           # mysql 驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ly.springcloud.entity         #entity 别名类所在包

eureka:
  client:
    #表示是否将自己注册进Eureka server 默认为true
    register-with-eureka: true
    #是否从Eureka server 中抓取已有的注册信息，默认为true,单节点无所谓集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  单机版
      #下面是集群版
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #eureka 注册服务中心添加自定义名称
    instance-id: payment8002
    # 显示注册服务的ip 地址
    prefer-ip-address: true
    # eureka client 向服务端发送心跳的时间 默认为30s
    lease-renewal-interval-in-seconds: 1
    #服务端收到客户端上一次等待的时间默认为90s 超时则将其删除
    lease-expiration-duration-in-seconds: 2


