server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    # false 则不注册到我们的服务注册中心
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: consumer-feign-hystrix

#启动断路器服务
feign:
  hystrix:
    enabled: true