server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
        #路由的id ,没有固定的规则但要保证唯一，建议配合服务名一起使用
        - id: payment_routh
          #配置后提供服务的路由地址
#          uri: http://localhost:8001
          # 通过服务名称动态匹配路由地址
          uri: lb://PAYMENT-SERVICE
          predicates:
            #断言路径相匹配进行路由
            - Path=/payment/get/**
            # 表明访问上面的请求必须在这个时间之后
#            - After=2020-07-12T21:23:59.992+08:00[Asia/Shanghai]
#            - Cookie=username,mly
            #请求头中要有X-Request-Id 属性并赋值为整数的正则表达式
#            - Header=X-Request-Id,\d+
            - Method=GET


        - id: payment_routh2
#          uri: http://localhost:8001
          # 通过服务名称动态匹配路由地址
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka 单机版
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true