server:
  port: 8080

spring:
  application:
    name: consumer-consul-order
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
